// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestionale_Libreria.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20240212161409_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Gestionale_Libreria.Models.Genere", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descrizione")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Generi");
                });

            modelBuilder.Entity("Gestionale_Libreria.Models.Libro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("idGenere")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idScaffale")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("prestito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("titolo")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Libri");
                });

            modelBuilder.Entity("Gestionale_Libreria.Models.Scaffale", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char>("code")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Libreria");
                });
#pragma warning restore 612, 618
        }
    }
}
